### ISSUE TITLE
I can't mint my SBT

### ISSUE THREAD

**Issue by ivankwan88** [near-ndc/i-am-human-dapp#166] opened 2023-08-06 14:37 UTC
![image](https://github.com/near-ndc/i-am-human-dapp/assets/112688882/4b2b900e-634c-4df4-bdd9-2110a2bd2496)

**Comment by ivankwan88** [comment] 2023-08-06 14:38
I can'r mint SBT

**Comment by ivankwan88** [comment] 2023-08-06 14:38
![image](https://github.com/near-ndc/i-am-human-dapp/assets/112688882/52b1b7ef-7502-4d01-966c-0d7c9421fe50)

**Comment by ivankwan88** [comment] 2023-08-06 14:39
![photo_2023-08-06_21-38-33](https://github.com/near-ndc/i-am-human-dapp/assets/112688882/a4a1b585-ba6f-449a-88d0-3a3456d8586e)

**Comment by Megha-Dev-19** [comment] 2023-08-09 12:05
hello @ivankwan88 
Our smart contract was impacted by Pagoda protocol runtime error introduced on Aug 3 on mainnet. Protocol runtime bug is now on mainnet.
you can fill this form, and we will inform you whenever we are live again (https://forms.gle/1SoT7d9924xXYTvA8)
thanks.

**Comment by Megha-Dev-19** [comment] 2023-08-11 03:53
@ivankwan88 the issue is fixed, you can now try to mint your token.
Thanks for reporting and apologises for the inconvenience caused.
I m closing the issue.

**Closed as completed by Megha-Dev-19** 2023-08-11 03:53 UTC
